### ISSUE TITLE
Optimizer Causes Item Stacking

### ISSUE THREAD

**Issue by utdrmac** [Selsion/DSPMods#7]
First off, let me say thank you for this mod. I certainly notice less framerate drop and more consistent 50s in UPS. One thing that I have noticed with this mod though, is that I get item stacking internally in machines nearest to ILS/PLS despite being at ratio. For example, Iron Plate is 1s/1 plate. Mark III belt is 30 items per second. You should be able to put 30 smelters outputting to that belt (going into ILS) without stacking inside the smelters. But, this has not been my experience. Most of the time, the 2 or 3 smelters closest to the ILS (on each line) will eventually fill up their internal stacks because they cannot output onto the full belt. But how can the belt be full with 27 smelters? I've been deleting 2-3 smelters off each line in order to keep smelters from stacking internally, but this seems to contradict ratio calculations. Any insight here? I'm not using any pilers anywhere, and I use Mk3 sorters.

**Comment by Selsion** [comment]
Thanks for submitting the issue. I'm not sure however that my mod is responsible for that. It doesn't touch sorter logic yet, and the only way it impacts belts is by adding multithreading to the logic that handles transferring items between belts and ILSs/PLSs. I wouldn't expect the multithreading implementation to impact the item transfer rate, since the same update methods should still be called once per tick. If you can confirm that it happens with the mod and doesn't happen without it, then that'd be helpful. An easy way to recreate such an issue (like a save file) would help the most.

I've seen this behaviour in-game before. One possibility is that it happens because of small gaps at the end of the belt when it's mostly full. Each item on a belt has a length of 10 units (technically 10 bytes in a memory buffer), so if a gap is shorter than that then an item won't fit. I think I remember seeing patch notes saying that sorters will try to squeeze items in to an extent anyway though.

There was a similar issue a while back with fractionators, which is now patched. On a mk3 belt items move at 5 units/tick, but at the time an item would have to be at the exact end of a belt in order to be inputted to a fractionator. If there was a gap of 2 units between an item and the end, then the belt would need an extra tick to move the item to the end of the belt. This resulted in fractonators being slightly slower than expected when the belt length between fractionators wasn't a multiple of 5 units. Perhaps something similar is happening here.

**Comment by soarqin** [comment]
I have met similar behaviour here after updating to 1.1.13: smelters and assemblers forge more items than expected, and output nearly infinite items when their storage cache reaches full.

**Comment by Selsion** [comment]
Thanks for the additional info. I took a closer look and found out that the build of the mod that I published had some prototype code left enabled, when I thought it was disabled. It was related to sorters knowing what items a factory building needs, where my patch would result in changes only when needed. This code should most likely be the issue since it was an unfinished prototype I made a while ago, so I removed it with version 1.1.14 of DSPOptimizations. Can you confirm if the bug is gone with this update?

**Comment by soarqin** [comment]
@Selsion 1.1.14 seems okay to me. Thanks for quick fix.

**Comment by utdrmac** [comment]
I must be missing something. There's been no commits to this repo since last May. Where is the current code (v1.1.14) being stored? The link at Thunderstore shows updated plugin but just references back to this github.

**Comment by NakiriFox** [comment]
https://thunderstore.io/c/dyson-sphere-program/p/Eirshy/ReBuffer/
maybe can fix it?
